server:
  port: ${PORT:8080}
  url: ${SERVER_URL:http://localhost:8080}

spring:
  application:
    name: ms-student
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool:
      max-idle-time: 10m
      validation-query: SELECT 1
      initial-size: 1
      max-size: 5

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
