server:
  port: 8082
  url: http://localhost:8082

spring:
  application:
    name: ms-student
  r2dbc:
    url: r2dbc:postgresql://ep-withered-shape-anlsd669-pooler.c-6.us-east-1.aws.neon.tech/duban_salas_35?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_mWdQ7hoGT3UF
    pool:
      max-idle-time: 10m
      validation-query: SELECT 1
      initial-size: 1
      max-size: 5

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html